<%@ page contentType="text/html; charset=UTF-8"%>
<%@ page import="java.util.*, java.sql.*" %>
<%@ page import="org.ffa.util.http.*, org.ffa.util.json.*, org.ffa.util.velocity.*, org.ffa.util.xml.*" %>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@taglib prefix="shiro" uri="http://shiro.apache.org/tags"%>
<%@taglib prefix="lk" uri="http://look.up.com.cn/" %>
<%@taglib prefix="pg" uri="http://app.zhubao.com.cn/" %>
